handle: figure
name: Figure
context:
  bleed: true
  sources:
  - src: https://placehold.it/1200x800
    size: '1200'
  - src: https://placehold.it/600x400
    size: '600'
  - src: https://placehold.it/300x200
    size: '300'
  caption: <p>Aspernatur neque <a href='#'>debitis atque saepe</a> magni praesentium eos.</p>
variants:
- name: default
  label: Picture
  context:
    type: picture
    icon: other/picture
- name: image
  label: Image
  context:
    type: image
    icon: other/picture
