name: Transporter
handle: transporter
display:
  background: "#eeebe2"
collated: true
context:
  title: Latest articles
  promos:
  - modifiers: ['transporter-child']
    headingLevel: h3
    url: http://google.com
    image:
      sources:
      - src: https://placehold.it/1600x900
        size: '1600'
      - src: https://placehold.it/1200x675
        size: '1200'
      - src: https://placehold.it/800x450
        size: '800'
      - src: https://placehold.it/400x225
        size: '400'
    meta: 
      type: article
      date: 2 days ago
    title: Oops!...I wrote a Britney blog post
  - modifiers: ['transporter-child']
    headingLevel: h3
    url: http://google.com
    image:
      sources:
      - src: https://placehold.it/1600x900
        size: '1600'
      - src: https://placehold.it/1200x675
        size: '1200'
      - src: https://placehold.it/800x450
        size: '800'
      - src: https://placehold.it/400x225
        size: '400'
    meta: 
      type: article
      date: 2 days ago
    title: Oops!...I wrote a Britney blog post
  - modifiers: ['transporter-child']
    headingLevel: h3
    url: http://google.com
    image:
      sources:
      - src: https://placehold.it/1600x900
        size: '1600'
      - src: https://placehold.it/1200x675
        size: '1200'
      - src: https://placehold.it/800x450
        size: '800'
      - src: https://placehold.it/400x225
        size: '400'
    meta: 
      type: article
      date: 2 days ago
    title: Oops!...I wrote a Britney blog post
variants:
  - name: Theme transporter
    context:
      type: theme
      title: Mind control
      introCopy: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
      themeUrl: http://google.co.uk
      promos:
      - modifiers: ['transporter-child']
        headingLevel: h3
        url: http://google.com
        image:
          sources:
          - src: https://placehold.it/1600x900
            size: '1600'
          - src: https://placehold.it/1200x675
            size: '1200'
          - src: https://placehold.it/800x450
            size: '800'
          - src: https://placehold.it/400x225
            size: '400'
        meta: 
          type: article
          date:
        title: life Before Death
      - modifiers: ['transporter-child']
        headingLevel: h3
        url: http://google.com
        image:
          sources:
          - src: https://placehold.it/1600x900
            size: '1600'
          - src: https://placehold.it/1200x675
            size: '1200'
          - src: https://placehold.it/800x450
            size: '800'
          - src: https://placehold.it/400x225
            size: '400'
        meta: 
          type: video
          length: "1:47"
          date:
        title: Depressed in Dhariva
      - modifiers: ['transporter-child']
        headingLevel: h3
        url: http://google.com
        image:
          sources:
          - src: https://placehold.it/1600x900
            size: '1600'
          - src: https://placehold.it/1200x675
            size: '1200'
          - src: https://placehold.it/800x450
            size: '800'
          - src: https://placehold.it/400x225
            size: '400'
        meta: 
          type: article
          date:
        title: "Inspired: Housewives & alchemists around a long table"

