name: List card
handle: list-card
context:
  heading: Latest
  items:
    - title: "Beatboxing tutorial #1: Using the air in your mouth"
      url: "#"
      meta: Today
    - title: "Lorem ispum dolor sit: Amet"
      url: "#"
      meta: Yesterday
    - title: "Fusce nunc lectus, rutrum sit amet nisi nec, euismod hendrerit eros"
      url: "#"
      meta: A week ago
    - title: "Lorem ispum dolor sit: Amet"
      url: "#"
      meta: 2 weeks ago
    - title: "Fusce nunc lectus, rutrum sit amet nisi nec, euismod hendrerit eros"
      url: "#"
      meta: 3 weeks ago
