version: 2
jobs:
  build:
    docker:
      - image: node:6.1.0
    working_directory: ~/wellcomecollection.org
    steps:
      - checkout
      - run:
          name: Build client
          command: ./build-client.sh
      - run:
          name: Build server
          command: ./build-server.sh
      - run:
          name: Test server
          command: ./test.sh server
      - add_ssh_keys
      - setup_remote_docker
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.1-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - deploy:
          name: Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker build -t wellcome/wellcomecollection:$CIRCLE_BUILD_NUM .
              docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
              docker push wellcome/wellcomecollection:$CIRCLE_BUILD_NUM
              pushd nginx-proxy && ./docker-build.sh $CIRCLE_BUILD_NUM && ./docker-push.sh && popd

              ./build-cardigan.sh
              ./build-speedtracker.sh
            fi
