name: button-link
handle: button-link
context:
  href: wellcomecollection.org
  text: this is a button
variants:
- name: with icon
  context:
    icon: actions/download-1
    iconExtraClasses: [icon--fill]
    text: this is a link with an icon
- name: light button
  context:
    modifierClasses: btn--light
    text: this is a link
- name: dark button with icon
  display:
    background: "#000"
  context:
    modifierClasses: btn--dark
    icon: actions/download-1
    iconExtraClasses: [icon--fill]
    text: this is a link
