version: 2
jobs:
  checkout_code:
    docker:
      - image: wellcome/node-docker:8.9.1
    working_directory: ~/wellcomecollection.org
    steps:
      - checkout
      - save_cache:
          key: repo_{{ .Environment.CIRCLE_SHA1 }}
          paths:
            -  ~/wellcomecollection.org
  install_server_modules:
    docker:
      - image: wellcome/node-docker:8.9.1
    working_directory: ~/wellcomecollection.org/server
    steps:
      - restore_cache:
          key: repo_{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Install server modules
          command: yarn install --production
      - save_cache:
          key: server_modules_node_8_{{ checksum "yarn.lock" }}
          paths:
            -  node_modules
  build_client:
    docker:
      - image: wellcome/node-docker:8.9.1
    working_directory: ~/wellcomecollection.org/client
    steps:
      - restore_cache:
          key: repo_{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Install client modules
          command: yarn install
      - run:
          name: Build client assets
          command: yarn run compile
      - save_cache:
          key: client_modules_node_8_{{ checksum "yarn.lock" }}
          paths:
            -  node_modules
      - save_cache:
          key: built_dist_{{ .Environment.CIRCLE_SHA1 }}
          paths:
            -  ~/wellcomecollection.org/dist
  build_exhibitions_webapp:
    docker:
      - image: wellcome/node-docker:8.9.1
    working_directory: ~/wellcomecollection.org/exhibitions/app
    steps:
      - restore_cache:
          key: repo_{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: server_modules_node_8_{{ checksum "../../server/yarn.lock" }}
      - restore_cache:
          key: built_dist_{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Install modules
          command: yarn install
      - run:
          name: Build prod config
          command: pushd ../../ && ./build_prod_config.py && popd
      - run:
          name: Build
          command: yarn run app:build
      - save_cache:
          key: built_exhibitions_webapp_{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - .dist
  deploy_exhibitions_webapp:
    docker:
      - image: wellcome/node-docker:8.9.1
    working_directory: ~/wellcomecollection.org
    steps:
      - restore_cache:
          key: repo_{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: built_exhibitions_webapp_{{ .Environment.CIRCLE_SHA1 }}
      - add_ssh_keys
      - setup_remote_docker
      - run:
          name: Deploy
          command: |
            docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
            CONTAINER_TAG=${CIRCLE_SHA1} docker-compose --file ./build/exhibitions_webapp.yml build
            CONTAINER_TAG=${CIRCLE_SHA1} docker-compose --file ./build/exhibitions_webapp.yml push
  build_events_webapp:
    docker:
      - image: wellcome/node-docker:8.9.1
    working_directory: ~/wellcomecollection.org/events/app
    steps:
      - restore_cache:
          key: repo_{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: server_modules_node_8_{{ checksum "../../server/yarn.lock" }}
      - restore_cache:
          key: built_dist_{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Install modules
          command: yarn install
      - run:
          name: Build prod config
          command: pushd ../../ && ./build_prod_config.py && popd
      - run:
          name: Build
          command: yarn run app:build
      - save_cache:
          key: built_events_webapp_{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - .dist
  deploy_events_webapp:
    docker:
      - image: wellcome/node-docker:8.9.1
    working_directory: ~/wellcomecollection.org
    steps:
      - restore_cache:
          key: repo_{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: built_events_webapp_{{ .Environment.CIRCLE_SHA1 }}
      - add_ssh_keys
      - setup_remote_docker
      - run:
          name: Deploy
          command: |
            docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
            CONTAINER_TAG=${CIRCLE_SHA1} docker-compose --file ./build/events_webapp.yml build
            CONTAINER_TAG=${CIRCLE_SHA1} docker-compose --file ./build/events_webapp.yml push
  build_common_webapp:
    docker:
      - image: wellcome/node-docker:8.9.1
    working_directory: ~/wellcomecollection.org
    steps:
      - restore_cache:
          key: repo_{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: server_modules_node_8_{{ checksum "server/yarn.lock" }}
      - restore_cache:
          key: built_dist_{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Build client
          command: ./build-client.sh
      - run:
          name: Build prod config
          command: ./build_prod_config.py
      - run:
          name: Build server
          command: ./build-server.sh $CIRCLE_SHA1
      - save_cache:
          key: built_server_{{ .Environment.CIRCLE_SHA1 }}
          paths:
            -  ~/wellcomecollection.org/server
      - save_cache:
          key: built_dist_{{ .Environment.CIRCLE_SHA1 }}
          paths:
            -  ~/wellcomecollection.org/dist
  test_common_webapp:
    docker:
      - image: wellcome/node-docker:8.9.1
    working_directory: ~/wellcomecollection.org
    steps:
      - restore_cache:
          key: repo_{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: server_modules_node_8_{{ checksum "server/yarn.lock" }}
      - restore_cache:
          key: built_server_{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Test server
          command: pushd server && yarn run test && popd
  deploy_common_webapp:
    docker:
      - image: wellcome/node-docker:8.9.1
    working_directory: ~/wellcomecollection.org
    steps:
      - restore_cache:
          key: repo_{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: built_server_{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: built_dist_{{ .Environment.CIRCLE_SHA1 }}
      - add_ssh_keys
      - setup_remote_docker
      - run:
          name: Deploy
          command: |
            docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
            python ./.circleci/deploy_and_build_docker.py './' 'wellcome/wellcomecollection' $CIRCLE_SHA1
            python ./.circleci/deploy_and_build_docker.py './nginx-proxy' 'wellcome/wellcomecollection-nginx-proxy' $CIRCLE_SHA1
            python ./.circleci/deploy_and_build_docker.py './router' 'wellcome/wellcomecollection-router' $CIRCLE_SHA1
            ./build-speedtracker.sh
  deploy_assets:
      docker:
        - image: node:8.9.1
      working_directory: ~/wellcomecollection.org/dist
      steps:
        - restore_cache:
            key: built_dist_{{ .Environment.CIRCLE_SHA1 }}
        - add_ssh_keys
        - run:
            name: Install AWS CLI
            command: |
              # Taken from
              # http://docs.aws.amazon.com/cli/latest/userguide/awscli-install-linux.html
              apt-get -y -qq update
              apt-get -y -qq install python3.4-dev
              curl -O https://bootstrap.pypa.io/get-pip.py
              python3.4 get-pip.py --user
              export PATH=~/.local/bin:$PATH
              pip install awscli --upgrade --user
              aws s3 sync --only-show-errors . s3://i.wellcomecollection.org
  deploy_cardigan:
    docker:
      - image: node:8.9.1
    working_directory: ~/wellcomecollection.org
    steps:
      - restore_cache:
          key: repo_{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: built_server_{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: built_dist_{{ .Environment.CIRCLE_SHA1 }}
      - add_ssh_keys
      - run:
          name: Install AWS CLI
          command: |
            # Taken from
            # http://docs.aws.amazon.com/cli/latest/userguide/awscli-install-linux.html
            apt-get -y -qq update
            apt-get -y -qq install python3.4-dev
            curl -O https://bootstrap.pypa.io/get-pip.py
            python3.4 get-pip.py --user
            export PATH=~/.local/bin:$PATH
            pip install awscli --upgrade --user
            ./build-cardigan.sh
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - checkout_code
      - install_server_modules:
          requires:
            - checkout_code
      - build_client:
          requires:
            - checkout_code
      - build_exhibitions_webapp:
          requires:
            - checkout_code
            - build_client
            - install_server_modules
      - deploy_exhibitions_webapp:
          requires:
            - build_exhibitions_webapp
          filters:
            branches:
              only:
                - master
      - build_events_webapp:
          requires:
            - checkout_code
            - build_client
            - install_server_modules
      - deploy_events_webapp:
          requires:
            - build_events_webapp
          filters:
            branches:
              only:
                - master
      - build:
          requires:
            - checkout_code
            - build_client
            - install_server_modules
      - test:
          requires:
            - checkout_code
            - build
      - deploy_assets:
          requires:
            - test
          filters:
            branches:
              only:
                - master
      - deploy_app:
          requires:
            - test
          filters:
            branches:
              only:
                - master
      - deploy_cardigan:
          requires:
            - test
          filters:
            branches:
              only:
                - master
