name: promo
context:
  image:
    sources:
    - src: https://placehold.it/1200x800
      size: '1200'
    - src: https://placehold.it/600x400
      size: '600'
    - src: https://placehold.it/300x200
      size: '300'

    alt: placeholder image
  intro: Article
  title: Animating the Body
  copy: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos eius debitis, ad unde laborum assumenda numquam suscipit sint iure itaque aut pariatur, neque omnis vel tenetur sapiente nam iusto quas.
