name: footer-social
handle: footer-social
display:
  background: "#1d1d1d"
context:
  items:
    - title: Twitter
      service: Twitter
      url: "#"
      icon: social/twitter
    - title: Facebook
      service: Facebook
      url: "#"
      icon: social/facebook
    - title: Instagram
      service: Instagram
      url: "#"
      icon: social/instagram
    - title: SoundCloud
      service: SoundCloud
      url: "#"
      icon: social/soundcloud
    - title: Tumblr
      service: Tumblr
      url: "#"
      icon: social/tumblr
    - title: YouTube
      service: YouTube
      url: "#"
      icon: social/youtube
    - title: TripAdvisor
      service: TripAdvisor
      url: "#"
      icon: social/tripadvisor
    - title: RSS
      service: RSS
      url: "#"
      icon: social/rss
