handle: footer-nav
name: Footer nav
display:
  background: "#010101"
context:
  navLinks:
  - href: "#"
    title: Visit us
  - href: "#"
    title: What's on
  - href: "#"
    title: Explore
  - href: "#"
    title: What we do
