name: Iframed Video
handle: iframed-video
status: ready
context:
  embedUrl: https://www.youtube.com/embed/bfXAlqx0H1g?version=3&rel=1&fs=1&autohide=2&showsearch=0&showinfo=1&iv_load_policy=1&wmode=transparent