handle: opening-hours
label: Opening hours
display:
  background: "#1d1d1d"
context:
  places:
  - id: galleries
    name: Galleries
    days:
    - name: Monday
      hours: Galleries closed
    - name: Tuesday
      hours: 10:00 - 18:00
    - name: Wednesday
      hours: 10:00 - 18:00
    - name: Thursday
      hours: 10:00 - 22:00
    - name: Friday
      hours: 10:00 - 18:00
    - name: Saturday
      hours: 10:00 - 18:00
    - name: Sunday
      hours: 11:00 - 18:00
  - id: library
    name: Library
    days:
    - name: Monday
      hours: 10:00 - 18:00
    - name: Tuesday
      hours: 10:00 - 18:00
    - name: Wednesday
      hours: 10:00 - 18:00
    - name: Thursday
      hours: 10:00 - 20:00
    - name: Friday
      hours: 10:00 - 18:00
    - name: Saturday
      hours: 10:00 - 18:00
    - name: Sunday
      hours: 10:00 - 16:00
  - id: restaurant
    name: Restaurant
    days:
    - name: Monday
      hours: Closed
    - name: Tuesday
      hours: 11:00 - 18:00
    - name: Wednesday
      hours: 11:00 - 18:00
    - name: Thursday
      hours: 11:00 - 22:00
    - name: Friday
      hours: 11:00 - 18:00
    - name: Saturday
      hours: 11:00 - 18:00
    - name: Sunday
      hours: 11:00 - 18:00
  - id: cafe
    name: Cafe
    days:
    - name: Monday
      hours: 08:30 - 18:00
    - name: Tuesday
      hours: 08:30 - 18:00
    - name: Wednesday
      hours: 08:30 - 18:00
    - name: Thursday
      hours: 08:30 - 22:00
    - name: Friday
      hours: 08:30 - 18:00
    - name: Saturday
      hours: 09:30 - 18:00
    - name: Sunday
      hours: 10:30 - 18:00
  - id: shop
    name: Shop
    days:
    - name: Monday
      hours: 09:00 - 18:00
    - name: Tuesday
      hours: 09:00 - 18:00
    - name: Wednesday
      hours: 09:00 - 18:00
    - name: Thursday
      hours: 09:00 - 22:00
    - name: Friday
      hours: 09:00 - 18:00
    - name: Saturday
      hours: 10:00 - 18:00
    - name: Sunday
      hours: 11:00 - 18:00
