handle: blockquote
context:
  body: "<p>It was a large room, heavily outfitted with the usual badly ventilated
    furnaces, rows of bubbling crucibles, and one stuffed alligator. Things floated
    in jars. The air smelled of a limited life expectancy.</p>"
  footer: "<footer class='blockquote__footer'>Emily Dickinson, <cite class='blockquote__cite'>I
    felt a funeral in my brain</cite></footer>"
notes: For pull quotes. Suited for more serious articles
variants:
- name: default
  context:
    modifiers:
    - with-marks
- name: Wellcome Bold
  context:
    modifiers:
    - with-marks
    - wb
  notes: For pull quotes. Suited for more informal articles
- name: Leterra
  context:
    modifiers:
    - lr
  notes: For text references
