name: Article
handle: article-template
context:
  inSection: explore
  article:
    headline: How cultural contexts can shape mental illness
    tags: "@tags.tags"
    author: "@author"
    mainMedia:
    - contentUrl: "https://placehold.it/1200x900"
      caption: "'Choose safer sex' poster with a photograph of two men in bed"
      width: 1200
      height: 900
    articleBody:
    - type: html
      value: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus at volutpat erat. Quisque non eros viverra, tincidunt mi a, interdum libero. Vestibulum efficitur ex sed est interdum, ac placerat enim blandit. Phasellus sodales velit non est bibendum tincidunt. Phasellus ut ligula at velit congue lobortis. Fusce at suscipit purus, ac tincidunt orci.</p>"
    - type: picture
      weight: supporting
      value:
        contentUrl: https://placehold.it/400x300
        caption: © Copyright Holder
        author: Author's name
        width: 400
        height: 300
        copyrightHolder: copyright holder
        fileFormat: png
        url: null
    - type: html
      value: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus at volutpat erat. Quisque non eros viverra, tincidunt mi a, interdum libero. Vestibulum efficitur ex sed est interdum, ac placerat enim blandit. Phasellus sodales velit non est bibendum tincidunt. Phasellus ut ligula at velit congue lobortis. Fusce at suscipit purus, ac tincidunt orci.</p>"
    - type: html
      value: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus at volutpat erat. Quisque non eros viverra, tincidunt mi a, interdum libero. Vestibulum efficitur ex sed est interdum, ac placerat enim blandit. Phasellus sodales velit non est bibendum tincidunt. Phasellus ut ligula at velit congue lobortis. Fusce at suscipit purus, ac tincidunt orci.</p>"
    - type: interview
      value: "@interview.interview"
    - type: html
      value: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus at volutpat erat. Quisque non eros viverra, tincidunt mi a, interdum libero. Vestibulum efficitur ex sed est interdum, ac placerat enim blandit. Phasellus sodales velit non est bibendum tincidunt. Phasellus ut ligula at velit congue lobortis. Fusce at suscipit purus, ac tincidunt orci.</p>"
    - type: picture
      value:
        contentUrl: https://placehold.it/400x300
        caption: © Copyright Holder
        author: Author's name
        width: 400
        height: 300
        copyrightHolder: copyright holder
        fileFormat: png
        url: null
    - type: html
      value: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus at volutpat erat. Quisque non eros viverra, tincidunt mi a, interdum libero. Vestibulum efficitur ex sed est interdum, ac placerat enim blandit. Phasellus sodales velit non est bibendum tincidunt. Phasellus ut ligula at velit congue lobortis. Fusce at suscipit purus, ac tincidunt orci.</p>"
    - type: html
      value: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus at volutpat erat. Quisque non eros viverra, tincidunt mi a, interdum libero. Vestibulum efficitur ex sed est interdum, ac placerat enim blandit. Phasellus sodales velit non est bibendum tincidunt. Phasellus ut ligula at velit congue lobortis. Fusce at suscipit purus, ac tincidunt orci.</p>"
    - type: html
      value: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus at volutpat erat. Quisque non eros viverra, tincidunt mi a, interdum libero. Vestibulum efficitur ex sed est interdum, ac placerat enim blandit. Phasellus sodales velit non est bibendum tincidunt. Phasellus ut ligula at velit congue lobortis. Fusce at suscipit purus, ac tincidunt orci.</p>"
    - type: picture
      weight: 'standalone'
      value:
        contentUrl: https://placehold.it/1200x600
        caption: © Copyright Holder
        author: Author's name
        width: 1200
        height: 600
        copyrightHolder: copyright holder
        fileFormat: png
        url: null
    - type: html
      value: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus at volutpat erat. Quisque non eros viverra, tincidunt mi a, interdum libero. Vestibulum efficitur ex sed est interdum, ac placerat enim blandit. Phasellus sodales velit non est bibendum tincidunt. Phasellus ut ligula at velit congue lobortis. Fusce at suscipit purus, ac tincidunt orci.</p>"
    - type: html
      value: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus at volutpat erat. Quisque non eros viverra, tincidunt mi a, interdum libero. Vestibulum efficitur ex sed est interdum, ac placerat enim blandit. Phasellus sodales velit non est bibendum tincidunt. Phasellus ut ligula at velit congue lobortis. Fusce at suscipit purus, ac tincidunt orci.</p>"
    - type: html
      value: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus at volutpat erat. Quisque non eros viverra, tincidunt mi a, interdum libero. Vestibulum efficitur ex sed est interdum, ac placerat enim blandit. Phasellus sodales velit non est bibendum tincidunt. Phasellus ut ligula at velit congue lobortis. Fusce at suscipit purus, ac tincidunt orci.</p>"
    - type: video
      value:
        name: Video name
        description: This is a description of the video
        embedUrl: https://youtube.com/embed/JMzQiwnQ0Bo
    - type: html
      value: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus at volutpat erat. Quisque non eros viverra, tincidunt mi a, interdum libero. Vestibulum efficitur ex sed est interdum, ac placerat enim blandit. Phasellus sodales velit non est bibendum tincidunt. Phasellus ut ligula at velit congue lobortis. Fusce at suscipit purus, ac tincidunt orci.</p>"
    - type: html
      value: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus at volutpat erat. Quisque non eros viverra, tincidunt mi a, interdum libero. Vestibulum efficitur ex sed est interdum, ac placerat enim blandit. Phasellus sodales velit non est bibendum tincidunt. Phasellus ut ligula at velit congue lobortis. Fusce at suscipit purus, ac tincidunt orci.</p>"
    - type: imageGallery
      weight: standalone
      value:
        name: Gallery name
        items:
        - contentUrl: https://placehold.it/400x300
          caption: © Copyright Holder
          author: Author's name
          width: 400
          height: 300
          copyrightHolder: copyright holder
          fileFormat: png
          url: null
        - contentUrl: https://placehold.it/500x200
          caption: © Copyright Holder
          author: Author's name
          width: 500
          height: 200
          copyrightHolder: copyright holder
          fileFormat: png
          url: null
        - contentUrl: https://placehold.it/600x300
          caption: © Copyright Holder
          author: Author's name
          width: 600
          height: 300
          copyrightHolder: copyright holder
          fileFormat: png
          url: null
        - contentUrl: https://placehold.it/600x300
          caption: © Copyright Holder
          author: Author's name
          width: 600
          height: 300
          copyrightHolder: copyright holder
          fileFormat: png
          url: null
        - contentUrl: https://placehold.it/600x300
          caption: © Copyright Holder
          author: Author's name
          width: 600
          height: 300
          copyrightHolder: copyright holder
          fileFormat: png
          url: null
        - contentUrl: https://placehold.it/750x250
          caption: © Copyright Holder
          author: Author's name
          width: 750
          height: 250
          copyrightHolder: copyright holder
          fileFormat: png
          url: null
        - contentUrl: https://placehold.it/900x500
          caption: © Copyright Holder
          author: Author's name
          width: 900
          height: 500
          copyrightHolder: copyright holder
          fileFormat: png
          url: null
    - type: imageGallery
      weight: standalone
      value:
        name: Gallery name
        items:
        - contentUrl: https://placehold.it/400x300
          caption: © Copyright Holder
          author: Author's name
          width: 400
          height: 300
          copyrightHolder: copyright holder
          fileFormat: png
          url: null
        - contentUrl: https://placehold.it/300x300
          caption: © Copyright Holder
          author: Author's name
          width: 300
          height: 300
          copyrightHolder: copyright holder
          fileFormat: png
          url: null
    - type: html
      value: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus at volutpat erat. Quisque non eros viverra, tincidunt mi a, interdum libero. Vestibulum efficitur ex sed est interdum, ac placerat enim blandit. Phasellus sodales velit non est bibendum tincidunt. Phasellus ut ligula at velit congue lobortis. Fusce at suscipit purus, ac tincidunt orci.</p>"
    - type: list
      value:
        name: List name
        items: [one, two, three]
    - type: html
      value: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus at volutpat erat. Quisque non eros viverra, tincidunt mi a, interdum libero. Vestibulum efficitur ex sed est interdum, ac placerat enim blandit. Phasellus sodales velit non est bibendum tincidunt. Phasellus ut ligula at velit congue lobortis. Fusce at suscipit purus, ac tincidunt orci.</p>"
