name: page description
handle: page-description
label: Page description
variants:
- name: default
  label: A (article)
  notes: Article title lock-up.
  context:
    modifiers:
    - a
    intro: States of Mind
    title: 'Inspired: Alchemists and housewives around a long table'
    publicationDate: September 9th 2016
- name: hn
  label: B (library item)
  notes: Library item title.
  context:
    modifiers:
    - b
    intro:
    title: On the Origin of Species by Means of Natural Selection, or the Preservation
      of Favoured Races in the Struggle for Life
    publicationDate:
