handle: quote
context:
  body: "<p>Said Hamlet to Ophelia,<br />
            I'll draw a sketch of thee,<br />
            What kind of pencil shall I use? <br />
            2B or not 2B? </p>"
  footer: "<footer class='quote__footer'>Spike Milligan,
           <cite class='quote__cite'>A Silly Poem</cite></footer>"
notes: For pull quotes. Suited for more serious articles
variants:
- name: default
  context:
    modifiers:
    - with-marks
- name: Wellcome Bold
  context:
    modifiers:
    - with-marks
    - wb
  notes: For pull quotes. Suited for more informal articles
- name: Lettera
  context:
    modifiers:
    - lr
  notes: For text references
- name: Block
  context:
    modifiers:
    - block
