context:
  icons:
  - modifierClasses: icon--fill
    icon: arrow-big
    title: Arrow
  - modifierClasses: icon--fill
    icon: arrow-small
    title: Arrow
  - modifierClasses: icon--fill
    icon: bookmark
    title: Bookmark
  - modifierClasses: icon--fill
    icon: chevron-big
    title: Chevron
  - modifierClasses: icon--fill
    icon: chevron-medium
    title: Chevron
  - modifierClasses: icon--fill
    icon: chevron-small
    title: Chevron
  - modifierClasses: icon--fill
    icon: citation
    title: Citation
  - modifierClasses: icon--fill
    icon: close
    title: Close
  - modifierClasses: icon--fill
    icon: collapse-active
    title: Collapse Active
  - modifierClasses: icon--fill
    icon: collapse-hover
    title: Collapse Hover
  - modifierClasses: icon--fill
    icon: comments
    title: Comments
  - modifierClasses: icon--fill
    icon: contact-1
    title: Contact
  - modifierClasses: icon--fill
    icon: contact-2
    title: Contact
  - modifierClasses: icon--fill
    icon: cross-big
    title: Cross
  - modifierClasses: icon--fill
    icon: cross-small
    title: Cross
  - modifierClasses: icon--fill
    icon: download-1
    title: Download
  - modifierClasses: icon--fill
    icon: download-2
    title: Download
  - modifierClasses: icon--fill
    icon: email
    title: Email
  - modifierClasses: icon--fill
    icon: embed
    title: Embed
  - modifierClasses: icon--fill
    icon: expand-default
    title: Expand
  - modifierClasses: icon--fill
    icon: expand-hover
    title: Expand
  - modifierClasses: icon--fill
    icon: filter
    title: Filter
  - modifierClasses: icon--fill
    icon: gallery-link
    title: Gallery
  - modifierClasses: icon--fill
    icon: grid
    title: Grid
  - modifierClasses: icon--fill
    icon: hierarchy-tree
    title: Hierarchy
  - modifierClasses: icon--fill
    icon: list
    title: List
  - modifierClasses: icon--fill
    icon: maximize
    title: Maximize
  - modifierClasses: icon--fill
    icon: menu
    title: Menu
  - modifierClasses: icon--fill
    icon: more-1
    title: More
  - modifierClasses: icon--fill
    icon: more-2
    title: More
  - modifierClasses: icon--fill
    icon: play
    title: Play
  - modifierClasses: icon--fill
    icon: plus-medium
    title: Plus
  - modifierClasses: icon--fill
    icon: plus-small
    title: Plus
  - modifierClasses: icon--stroke
    icon: print
    title: Print
  - modifierClasses: icon--fill
    icon: request
    title: Request
  - modifierClasses: icon--fill
    icon: save-to-account-1
    title: Save to account
  - modifierClasses: icon--fill
    icon: save-to-account-2
    title: Save to account
  - modifierClasses: icon--fill
    icon: save-to-account-3
    title: Save to account
  - modifierClasses: icon--fill
    icon: search
    title: Search
  - modifierClasses: icon--fill
    icon: share-1
    title: Share
  - modifierClasses: icon--fill
    icon: share-2
    title: Share
  - modifierClasses: icon--fill
    icon: sublevels
    title: Sub levels
  - modifierClasses: icon--fill
    icon: user
    title: User
  - modifierClasses: icon--fill
    icon: view
    title: View
  - modifierClasses: icon--fill
    icon: volume
    title: Volume
  - modifierClasses: icon--fill
    icon: audio-1
    title: Audio
  - modifierClasses: icon--fill
    icon: audio-2
    title: Audio
  - modifierClasses: icon--fill
    icon: audio-3
    title: Audio
  - modifierClasses: icon--fill
    icon: book
    title: Book
  - modifierClasses: icon--fill
    icon: databases-and-websites
    title: Databases and websites
  - modifierClasses: icon--fill
    icon: image
    title: Image
  - modifierClasses: icon--fill
    icon: manuscript
    title: Manuscript
  - modifierClasses: icon--fill
    icon: map
    title: Map
  - modifierClasses: icon--fill
    icon: video
    title: Video
  - modifierClasses: icon--fill
    icon: clock
    title: Clock
  - modifierClasses: icon--fill
    icon: comments-2
    title: Comments
  - modifierClasses: icon--fill
    icon: picture
    title: Picture
  - modifierClasses: icon--fill
    icon: facebook
    title: Facebook
  - modifierClasses: icon--fill
    icon: google-plus
    title: Google Plus
  - modifierClasses: icon--fill
    icon: instagram
    title: Instagram
  - modifierClasses: icon--fill
    icon: pinterest
    title: Pinterest
  - modifierClasses: icon--fill
    icon: twitter
    title: Twitter
