# TODO: collect these values from client/scss/utilies/_variables.scss
context:
  primary:
  - name: seaweed
    hex: "#088574"
  - name: lime
    hex: "#0aa38f"
  - name: white
    hex: "#fff"
  - name: cream
    hex: "#eeebe2"
  - name: black
    hex: "#1d1d1d"
  - name: dark-black
    hex: "#010101"
  secondary:
  - name: turquoise-graphics
    hex: "#5cb8bf"
  - name: turquoise-text
    hex: "#367378"
  - name: teal
    hex: "#006272"
  - name: petrol
    hex: "#00424d"
  - name: purple-graphics
    hex: "#b67bc2"
  - name: purple-text
    hex: "#895791"
  - name: indigo
    hex: "#46284d"
  - name: red-graphics
    hex: "#ff4355"
  - name: red-text
    hex: "#c72e3d"
  - name: orange-graphics
    hex: "#e87500"
  - name: orange-text
    hex: "#ad4e00"
  - name: yellow
    hex: "#ffce3c"
  - name: pewter
    hex: "#717171"
  - name: silver
    hex: "#8f8f8f"
  - name: smoke
    hex: "#e8e8e8"
  - name: pumice
    hex: "#d9d6ce"
  - name: charcoal
    hex: "#323232"
